### ISSUE TITLE
Plans cut-off

### ISSUE THREAD

**Issue by GoogleCodeExporter** [grinnellplans/grinnellplans-php#273] opened 2015-05-31 18:08 UTC
```
Username: [wheelerj]
Revision: 659
URL: www.grinnellplans.com/read.php?searchname=thorne
User-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/537.36 
(KHTML, like Gecko) Chrome/40.0.2214.94 Safari/537.36

How can we reproduce the problem?
1. Unsure. On May 12, I noticed that several days of updates had been chopped 
off from the bottom of my plan.
2.
3.

What is the expected output? What do you see instead?

Ideally, i would like my plan to stop randomly deleting large chunks of itself, 
but I know this is a very long-term ongiong issue, so I'm just offering this up 
as a data point.

```

Original issue reported on code.google.com by `jenniero...@gmail.com` on 17 May 2015 at 12:19

**Comment by iangreenleaf** [comment] 2015-06-01 04:04
Hmm. This was happening frequently at one point, but we committed some changes a while ago that we hoped had taken care of the issue. Sadly this suggests it's still possible. Closing this as a duplicate of #164, but if you happen to have it occur again and catch it right away, let us know any details that might be relevant. For example, how long your plan was before it got chopped off, if you're on a slow or inconsistent internet connection, what type of computer and operating system you're running, etc.

**Closed by iangreenleaf** 2015-06-01 04:04 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
